package crypto

import (
	"bytes"
	"testing"
)

func TestGenerateRoomKey(t *testing.T) {
	raw, err := GenerateRoomKey()
	if err != nil {
		t.Fatalf("GenerateRoomKey failed: %v", err)
	}

	if len(raw) != 16 {
		t.Errorf("key length = %d, want 16 bytes", len(raw))
	}

	// Must format into 4 groups of 8 hex chars separated by dashes.
	key := FormatRoomKey(raw)
	if len(key) != 35 {
		t.Errorf("formatted key length = %d, want 35", len(key))
	}

	// And parse back to the same bytes.
	parsed, err := ParseRoomKey(key)
	if err != nil {
		t.Fatalf("ParseRoomKey failed: %v", err)
	}
	if !bytes.Equal(parsed, raw) {
		t.Error("parsed key does not match generated bytes")
	}
}

func TestParseRoomKeyRoundTrip(t *testing.T) {
	generated, _ := GenerateRoomKey()
	key := FormatRoomKey(generated)

	raw, err := ParseRoomKey(key)
	if err != nil {
		t.Fatalf("ParseRoomKey failed: %v", err)
	}
	if !bytes.Equal(raw, generated) {
		t.Error("round-trip failed: parsed bytes differ from generated bytes")
	}
}

func TestParseRoomKeyInvalid(t *testing.T) {
	cases := []struct {
		name string
		key  string
	}{
		{"too short", "ABC"},
		{"too long", "ABCDEFGH-0123456789ABCDEF-0123456789ABCDEF"},
		{"invalid hex", "ZZZZZZZZ-00000000-00000000-00000000"},
		{"empty", ""},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := ParseRoomKey(tc.key)
			if err == nil {
				t.Errorf("expected error for %q, got nil", tc.key)
			}
		})
	}
}

func TestDeriveServiceName(t *testing.T) {
	key := []byte{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}
	name1 := DeriveServiceName(key)
	name2 := DeriveServiceName(key)

	// Same key → same name.
	if name1 != name2 {
		t.Errorf("same key produced different names: %s != %s", name1, name2)
	}

	// Different key → different name.
	key2 := []byte{16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1}
	name3 := DeriveServiceName(key2)
	if name1 == name3 {
		t.Errorf("different keys produced same name: %s", name1)
	}

	// Must start with "godrop-".
	if len(name1) < 8 || name1[:7] != "godrop-" {
		t.Errorf("name = %q, want prefix 'godrop-'", name1)
	}
}

func TestDeriveAuthKeyDifferentKeys(t *testing.T) {
	shared := make([]byte, 32)
	hostPub := make([]byte, 65)
	recvPub := make([]byte, 65)
	roomKey1 := []byte("0123456789ABCDEF")
	roomKey2 := []byte("FEDCBA9876543210")

	key1, err := DeriveAuthKey(shared, hostPub, recvPub, roomKey1)
	if err != nil {
		t.Fatalf("DeriveAuthKey failed: %v", err)
	}
	key2, err := DeriveAuthKey(shared, hostPub, recvPub, roomKey2)
	if err != nil {
		t.Fatalf("DeriveAuthKey failed: %v", err)
	}

	if bytes.Equal(key1, key2) {
		t.Error("different room keys produced same auth key")
	}
}

func TestAuthTagVerification(t *testing.T) {
	authKey := make([]byte, 32)
	for i := range authKey {
		authKey[i] = byte(i)
	}

	hostTag := ComputeAuthTag(authKey, AuthRoleHost)
	receiverTag := ComputeAuthTag(authKey, AuthRoleReceiver)

	// Tags for different roles must differ.
	if bytes.Equal(hostTag, receiverTag) {
		t.Error("host and receiver tags should differ")
	}

	// Each tag must verify against its own role.
	if !VerifyAuthTag(authKey, AuthRoleHost, hostTag) {
		t.Error("host tag failed verification")
	}
	if !VerifyAuthTag(authKey, AuthRoleReceiver, receiverTag) {
		t.Error("receiver tag failed verification")
	}

	// Cross-role verification must fail.
	if VerifyAuthTag(authKey, AuthRoleHost, receiverTag) {
		t.Error("receiver tag should not verify as host")
	}
	if VerifyAuthTag(authKey, AuthRoleReceiver, hostTag) {
		t.Error("host tag should not verify as receiver")
	}

	// Wrong auth key must fail.
	wrongKey := make([]byte, 32)
	wrongKey[0] = 0xFF
	if VerifyAuthTag(wrongKey, AuthRoleHost, hostTag) {
		t.Error("wrong auth key should fail verification")
	}
}
